// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJVMUoXOLnCtR4ADHwnLTBmsKRV5_iO1c',
    appId: '1:21509981807:web:bdbb86bd0c923868092f9a',
    messagingSenderId: '21509981807',
    projectId: 'yalapay-t5',
    authDomain: 'yalapay-t5.firebaseapp.com',
    storageBucket: 'yalapay-t5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEKnb2LdFUVqFi7C3o0Nobl1LA9Ho6Dhk',
    appId: '1:21509981807:android:83498cd55bfebfce092f9a',
    messagingSenderId: '21509981807',
    projectId: 'yalapay-t5',
    storageBucket: 'yalapay-t5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr3yN5LH887KNphQASVMKlENJ5CnxKNio',
    appId: '1:21509981807:ios:48071d49ce13ac86092f9a',
    messagingSenderId: '21509981807',
    projectId: 'yalapay-t5',
    storageBucket: 'yalapay-t5.firebasestorage.app',
    iosBundleId: 'com.example.yallaPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr3yN5LH887KNphQASVMKlENJ5CnxKNio',
    appId: '1:21509981807:ios:48071d49ce13ac86092f9a',
    messagingSenderId: '21509981807',
    projectId: 'yalapay-t5',
    storageBucket: 'yalapay-t5.firebasestorage.app',
    iosBundleId: 'com.example.yallaPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJVMUoXOLnCtR4ADHwnLTBmsKRV5_iO1c',
    appId: '1:21509981807:web:8a8a01c7b40cb8de092f9a',
    messagingSenderId: '21509981807',
    projectId: 'yalapay-t5',
    authDomain: 'yalapay-t5.firebaseapp.com',
    storageBucket: 'yalapay-t5.firebasestorage.app',
  );

}